isaacsim.replicator.agent:
  version: 0.7.19
  global:
    seed: 35
    simulation_length: 3000 # 100 seconds
  scene:
    asset_path: "${TICVLA_DYNANAV_ROOT}/assets/outdoor_small.usd"
  sensor:
    camera_num: 0
  character:
    asset_path:
    command_file: outdoor_character_command.txt
    num: 200
  robot:
    command_file: outdoor_robot_command.txt
    nova_carter_num: 0
    transporter_num: 0
    write_data: true
  replicator:
    writer: IRABasicWriter
    parameters:
      output_dir: "${TICVLA_DYNANAV_ROOT}/output/outdoor"
      object_info_bounding_box_2d_tight: false
      object_info_bounding_box_2d_loose: false
      object_info_bounding_box_3d: false
      agent_info_skeleton_data: false
      semantic_filter_predicate: class:character|robot;id:*
      image_output_format: jpg
      rgb: true
      camera_params: true
